### ISSUE TITLE
support multiple versions of glibc since the structures are changing

### ISSUE THREAD

**Issue by fidgetingbits** [nccgroup/libptmalloc#5]
this can be done by introducing a new ptversion command it lets you specify a supported version, and we can also add support for a heuristic that tries to guess the version. we can walk the bins for a guessed layout, and test pointers that don't point back to the main arena to see if this size actually correlates to the guessed index, in if not we can adjust the off said for that bin so that at lines up correctly and do further sanity tests

**Comment by saidelike** [comment]
Not relevant anymore so closing
